# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://lert-web-exhausted-serval-ki.mybluemix.net/")
    self.driver.set_window_size(651, 602)
    self.driver.find_element(By.CSS_SELECTOR, ".r-uz4sb0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".r-dhbnww:nth-child(1)").click()
    assert self.driver.switch_to.alert.text == "Navigate to Terms of User"
    self.driver.find_element(By.CSS_SELECTOR, ".r-dhbnww:nth-child(2)").click()
    assert self.driver.switch_to.alert.text == "IBM Internal Privacy Statement"
    self.driver.find_element(By.CSS_SELECTOR, ".css-1hf3ou5:nth-child(3)").click()
    assert self.driver.switch_to.alert.text == "Feedback"
    self.driver.find_element(By.CSS_SELECTOR, ".r-1b43r93:nth-child(4)").click()
    assert self.driver.switch_to.alert.text == "Bussiness Conduct Guidelines"
  
