export type ICAType = {
    id: string;
    status: string;
    totalBilling: string;
    icaCode: string,
    icaCore: string,
    year: string,
    idPlanning: string
    icaOwner: string,
    budget: string,
    country: string,
    depto: string,
    frequencyBill: string,
    cc: string,
    ctyNamePerf: string,
    ctyNameReq: string,
    rCtyPerf: string,
    rCtyReq: string,
    division: string,
    major: string,
    minor: string,
    leru: string,
    description: string,
    type: string,
    nec: string,
    totalPlusTaxes: string,
    startDate: string,
    endDate: string,
}